package main

import (
	"net/http"
)

func staticRoutes(mux *http.ServeMux) {
	fs := http.FileServer(http.Dir("./static"))
	mux.Handle("/static/", http.StripPrefix("/static/", fs))
}

func templatesRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/", homeHandlerTplt)
	mux.HandleFunc("/help", helpHandlerTplt)
	mux.HandleFunc("/contact", contactHandlerTplt)
	mux.HandleFunc("/bootstrap", bootstrapHandlerTplt)
	mux.HandleFunc("/clone", cloneHandlerTplt)
	mux.HandleFunc("/cmd", cmdHandlerTplt)
	mux.HandleFunc("/config", configHandlerTplt)
	mux.HandleFunc("/convert", convertHandlerTplt)
	mux.HandleFunc("/cp", cpHandlerTplt)
	mux.HandleFunc("/create", createHandlerTplt)
	mux.HandleFunc("/destroy", destroyHandlerTplt)
	mux.HandleFunc("/etcupdate", etcupdateHandlerTplt)
	mux.HandleFunc("/export", exportHandlerTplt)
	mux.HandleFunc("/htop", htopHandlerTplt)
	mux.HandleFunc("/import", importHandlerTplt)
	mux.HandleFunc("/jcp", jcpHandlerTplt)
	mux.HandleFunc("/limits", limitsHandlerTplt)
	mux.HandleFunc("/list", listHandlerTplt)
	mux.HandleFunc("/migrate", migrateHandlerTplt)
	mux.HandleFunc("/mount", mountHandlerTplt)
	mux.HandleFunc("/network", networkHandlerTplt)
	mux.HandleFunc("/pkg", pkgHandlerTplt)
	mux.HandleFunc("/rcp", rcpHandlerTplt)
	mux.HandleFunc("/rename", renameHandlerTplt)
	mux.HandleFunc("/restart", restartHandlerTplt)
	mux.HandleFunc("/service", serviceHandlerTplt)
	mux.HandleFunc("/setup", setupHandlerTplt)
	mux.HandleFunc("/start", startHandlerTplt)
	mux.HandleFunc("/stop", stopHandlerTplt)
	mux.HandleFunc("/sysrc", sysrcHandlerTplt)
	mux.HandleFunc("/tags", tagsHandlerTplt)
	mux.HandleFunc("/template", templateHandlerTplt)
	mux.HandleFunc("/top", topHandlerTplt)
	mux.HandleFunc("/umount", umountHandlerTplt)
	mux.HandleFunc("/update", updateHandlerTplt)
	mux.HandleFunc("/upgrade", upgradeHandlerTplt)
}

func dataRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /bootstrap", loggingMiddleware(bootstrapHandler))
	mux.HandleFunc("POST /clone", loggingMiddleware(cloneHandler))
	mux.HandleFunc("POST /cmd", loggingMiddleware(cmdHandler))
	mux.HandleFunc("POST /config", loggingMiddleware(configHandler))
	mux.HandleFunc("POST /convert", loggingMiddleware(convertHandler))
	mux.HandleFunc("POST /cp", loggingMiddleware(cpHandler))
	mux.HandleFunc("POST /create", loggingMiddleware(createHandler))
	mux.HandleFunc("POST /destroy", loggingMiddleware(destroyHandler))
	mux.HandleFunc("POST /etcupdate", loggingMiddleware(etcupdateHandler))
	mux.HandleFunc("POST /export", loggingMiddleware(exportHandler))
	mux.HandleFunc("POST /htop", loggingMiddleware(htopHandler))
	mux.HandleFunc("POST /import", loggingMiddleware(importHandler))
	mux.HandleFunc("POST /jcp", loggingMiddleware(jcpHandler))
	mux.HandleFunc("POST /limits", loggingMiddleware(limitsHandler))
	mux.HandleFunc("POST /list", loggingMiddleware(listHandler))
	mux.HandleFunc("POST /migrate", loggingMiddleware(migrateHandler))
	mux.HandleFunc("POST /mount", loggingMiddleware(mountHandler))
	mux.HandleFunc("POST /network", loggingMiddleware(networkHandler))
	mux.HandleFunc("POST /pkg", loggingMiddleware(pkgHandler))
	mux.HandleFunc("POST /rcp", loggingMiddleware(rcpHandler))
	mux.HandleFunc("POST /rename", loggingMiddleware(renameHandler))
	mux.HandleFunc("POST /restart", loggingMiddleware(restartHandler))
	mux.HandleFunc("POST /service", loggingMiddleware(serviceHandler))
	mux.HandleFunc("POST /setup", loggingMiddleware(setupHandler))
	mux.HandleFunc("POST /start", loggingMiddleware(startHandler))
	mux.HandleFunc("POST /stop", loggingMiddleware(stopHandler))
	mux.HandleFunc("POST /sysrc", loggingMiddleware(sysrcHandler))
	mux.HandleFunc("POST /tags", loggingMiddleware(tagsHandler))
	mux.HandleFunc("POST /template", loggingMiddleware(templateHandler))
	mux.HandleFunc("POST /top", loggingMiddleware(topHandler))
	mux.HandleFunc("POST /umount", loggingMiddleware(umountHandler))
	mux.HandleFunc("POST /update", loggingMiddleware(updateHandler))
	mux.HandleFunc("POST /upgrade", loggingMiddleware(upgradeHandler))
}
