basePath: /
definitions:
  main.bootstrapModel:
    properties:
      options:
        example: -x
        format: string
        type: string
      release|template:
        example: 14.3-RELEASE
        format: string
        type: string
      update|arch:
        example: --i386
        format: string
        type: string
    type: object
  main.cloneModel:
    properties:
      ip:
        example: n.n.n.n
        format: string
        type: string
      new_name:
        example: new_jail_name
        format: string
        type: string
      options:
        example: -a|-l|-x
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
    type: object
  main.cmdModel:
    properties:
      command:
        example: ls -l
        format: string
        type: string
      options:
        example: -a|-x
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
    type: object
  main.configModel:
    properties:
      action:
        example: get|set
        format: string
        type: string
      options:
        example: -x
        format: string
        type: string
      property:
        example: ip4.addr
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
      value:
        example: depends on property
        format: string
        type: string
    type: object
  main.consoleModel:
    properties:
      options:
        example: -a|-x
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
      user:
        example: root
        format: string
        type: string
    type: object
  main.convertModel:
    properties:
      options:
        example: -a|-y|-x
        format: string
        type: string
      release:
        example: myrelease
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
    type: object
  main.cpModel:
    properties:
      hostpath:
        example: /host/path
        format: string
        type: string
      jailpath:
        example: /jail/path
        format: string
        type: string
      options:
        example: -q|-x
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
    type: object
  main.createModel:
    properties:
      iface:
        example: bastille0
        format: string
        type: string
      ip:
        example: n.n.n.n
        format: string
        type: string
      ipip:
        example: n.n.n.n,i.i.i.i
        format: string
        type: string
      name:
        example: jail_name
        format: string
        type: string
      options:
        example: -B|-C|-D|-E|-g|-L|-M|-n|--no-validate|--no-boot|-p|-T|-V|-v|-x|-Z
        format: string
        type: string
      release:
        example: 14.3-RELEASE
        format: string
        type: string
      value:
        example: ""
        format: string
        type: string
      vlanid:
        example: vlan10
        format: string
        type: string
      zfsoptions:
        example: ""
        format: string
        type: string
    type: object
  main.destroyModel:
    properties:
      jail|release:
        example: jail_target or release
        format: string
        type: string
      options:
        example: -a|-c|-f|-y|-x
        format: string
        type: string
    type: object
  main.editModel:
    properties:
      file:
        example: file_name
        format: string
        type: string
      options:
        example: -x
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
    type: object
  main.etcupdateModel:
    properties:
      action:
        example: diff|resolve|update
        format: string
        type: string
      bootstrap|target:
        example: jail_name|bootstrap
        format: string
        type: string
      options:
        example: -d|-f|-x
        format: string
        type: string
      release:
        example: 14.3-RELEASE
        format: string
        type: string
    type: object
  main.exportModel:
    properties:
      options:
        example: -a|--gz|-r|-s|--tgz|--txz|-v|--xz|-x
        format: string
        type: string
      path:
        example: /host/path
        format: string
        type: string
      target:
        example: jail_target
        format: string
        type: string
    type: object
host: 127.0.0.1:80
info:
  contact: {}
  description: API interface to FreeBSD bastille
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Bastille-Web
  version: "1.0"
paths:
  /bootstrap:
    post:
      consumes:
      - application/json
      description: The bootstrap sub-command is used to download and extract releases
        and templates for use with Bastille containers. A valid release is needed
        before containers can be created. Templates are optional but are managed in
        the same manner.
      parameters:
      - description: bootstrap
        in: body
        name: bootstrap
        required: true
        schema:
          $ref: '#/definitions/main.bootstrapModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: bootstrap command
      tags:
      - bootstrap
  /clone:
    post:
      consumes:
      - application/json
      description: Clone/duplicate an existing jail to a new jail.
      parameters:
      - description: clone
        in: body
        name: clone
        required: true
        schema:
          $ref: '#/definitions/main.cloneModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: clone command
      tags:
      - clone
  /cmd:
    post:
      consumes:
      - application/json
      description: Execute commands inside targeted jail(s).
      parameters:
      - description: cmd
        in: body
        name: cmd
        required: true
        schema:
          $ref: '#/definitions/main.cmdModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: cmd command
      tags:
      - cmd
  /config:
    post:
      consumes:
      - application/json
      description: Get, set or remove properties from targeted jail(s).
      parameters:
      - description: config
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/main.configModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: config command
      tags:
      - config
  /console:
    post:
      consumes:
      - application/json
      description: Launch a login shell into the jail. Default is password- less root
        login.
      parameters:
      - description: config
        in: body
        name: console
        required: true
        schema:
          $ref: '#/definitions/main.consoleModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: console command
      tags:
      - console
  /convert:
    post:
      consumes:
      - application/json
      description: Convert a thin jail to a thick jail. Convert a thick jail to a
        custom release.
      parameters:
      - description: config
        in: body
        name: convert
        required: true
        schema:
          $ref: '#/definitions/main.convertModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: convert command
      tags:
      - convert
  /cp:
    post:
      consumes:
      - application/json
      description: Copy files from host to jail(s).
      parameters:
      - description: cp
        in: body
        name: cp
        required: true
        schema:
          $ref: '#/definitions/main.cpModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: cp command
      tags:
      - cp
  /create:
    post:
      consumes:
      - application/json
      description: Create a jail uning any available bootstrapped release. To create
        a jail, simply provide a name, bootstrapped release, and IP address.
      parameters:
      - description: create
        in: body
        name: create
        required: true
        schema:
          $ref: '#/definitions/main.createModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: create command
      tags:
      - create
  /destroy:
    post:
      consumes:
      - application/json
      description: Destroy jails or releases.
      parameters:
      - description: destroy
        in: body
        name: destroy
        required: true
        schema:
          $ref: '#/definitions/main.destroyModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: destroy command
      tags:
      - destroy
  /edit:
    post:
      consumes:
      - application/json
      description: Edit jail config files.
      parameters:
      - description: edit
        in: body
        name: edit
        required: true
        schema:
          $ref: '#/definitions/main.editModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: edit command
      tags:
      - edit
  /etcupdate:
    post:
      consumes:
      - application/json
      description: This command will update the contents of /etc inside a jail. It
        should be run after a jail upgrade.
      parameters:
      - description: etcupdate
        in: body
        name: etcupdate
        required: true
        schema:
          $ref: '#/definitions/main.etcupdateModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: etcupdate command
      tags:
      - etcupdate
  /export:
    post:
      consumes:
      - application/json
      description: Exporting a container creates an archive or image that can be sent
        to a different machine to be imported later. These exported archives can be
        used as container backups.
      parameters:
      - description: export
        in: body
        name: export
        required: true
        schema:
          $ref: '#/definitions/main.exportModel'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: export command
      tags:
      - export
swagger: "2.0"
